<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_assignment_lateReportskeyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>c33fdebd-924a-4d1a-a47a-67387312fd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-sidenav[@id='snav']/div/app-sidebar/mat-nav-list/mat-list-item[8]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e90bd600-97ba-42e3-809e-a752fbbfaaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>fd04e03b-6cac-4bb0-ab00-4d57a51cafca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>98829d20-5ecd-49b1-9da3-95fc259fab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>assignment_lateReportskeyboard_arrow_down</value>
      <webElementGuid>bad121a8-d06d-4299-b2c3-04cdf7534f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snav&quot;)/div[@class=&quot;mat-drawer-inner-container ng-tns-c67-3&quot;]/app-sidebar[@class=&quot;app-sidebar ng-tns-c67-3&quot;]/mat-nav-list[@class=&quot;mat-nav-list mat-list-base&quot;]/mat-list-item[@class=&quot;mat-list-item mat-focus-indicator ng-star-inserted&quot;]/span[@class=&quot;mat-list-item-content&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>c8d7f582-b222-4e23-ab62-7ec0dd50c152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-sidenav[@id='snav']/div/app-sidebar/mat-nav-list/mat-list-item[8]/span/a</value>
      <webElementGuid>0635e332-02cc-49a0-a9b3-8f3161973067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track &amp; Trace'])[1]/following::a[1]</value>
      <webElementGuid>0af98407-e9fb-44b5-aadf-8d7eb47dc80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Shipping Fee'])[1]/following::a[2]</value>
      <webElementGuid>d39b4ba1-d28c-4a3a-a962-85d01c145148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History Scan'])[1]/preceding::a[1]</value>
      <webElementGuid>f23b7ece-ce17-4386-82c0-e474108f90d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[5]</value>
      <webElementGuid>5c3227a6-4e57-4c56-ae71-6978fd12fc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-list-item[8]/span/a</value>
      <webElementGuid>8fb69d27-ae15-42b8-a1cf-444fde3a5546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'assignment_lateReportskeyboard_arrow_down' or . = 'assignment_lateReportskeyboard_arrow_down')]</value>
      <webElementGuid>c7159ed6-6804-4d3f-b25b-82b2ced3f438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
