<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Bagging</name>
   <tag></tag>
   <elementGuidId>0a5d8df7-bde3-4fa2-a24e-5330f5b52483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.page-title.text-themecolor.m-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/following::h5[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>d96212e3-0157-485b-81d7-c89c0e5f9e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title text-themecolor m-0</value>
      <webElementGuid>1ee10902-7301-43af-8532-b689076e805c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagging</value>
      <webElementGuid>5a54cad2-2d3e-4d19-8f18-ba57f876e7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container example-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content page-wrapper&quot;]/app-breadcrumb[1]/div[@class=&quot;page-breadcrumb p-t-10 p-b-10 bg-white p-l-5 ng-star-inserted&quot;]/div[1]/div[@class=&quot;align-self-center text-center&quot;]/h5[@class=&quot;page-title text-themecolor m-0&quot;]</value>
      <webElementGuid>ea0a9fd1-0b6d-43d3-b0c2-040627fef8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/following::h5[1]</value>
      <webElementGuid>2e88eb22-3585-4868-b5e6-783efb9e42fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification'])[1]/following::h5[1]</value>
      <webElementGuid>c2fd6600-8bc6-4f29-a03f-8e0a461ffb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::h5[1]</value>
      <webElementGuid>6e9e3377-6029-48d1-9354-ad146e6607f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[1]/preceding::h5[1]</value>
      <webElementGuid>b9899eaf-64ad-4369-84d6-b728aa8b7a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>4e649fdb-c8bf-4b77-84a1-5d79e66531a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Bagging' or . = 'Bagging')]</value>
      <webElementGuid>4819808b-293b-4411-8b2c-2a06e9861372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
