<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to App_mat-input-0</name>
   <tag></tag>
   <elementGuidId>f50fb8c0-1be9-427d-a8c6-ba30c14d78ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b95ca659-7a7b-4b13-bda2-b4f0b63366ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c105-0 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>0cb706ac-c7c2-44e9-8305-0ef17d9314dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-0</value>
      <webElementGuid>e652ad09-8d43-4363-98b1-d977f9b6c4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>6d44517a-b209-4f50-8ade-40bf4705a036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d51ce704-699a-4b02-80e3-4675dda44103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ae0e2f2-8d4f-465d-bd27-afa426d4fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-0&quot;)</value>
      <webElementGuid>05405ca7-0c27-44b6-b94d-7f49bc9c9d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-0']</value>
      <webElementGuid>7d38a7f1-5e17-4676-b962-c1e3a51dcba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aa338926-5c84-46fc-8f23-14144dbe4051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-0']</value>
      <webElementGuid>14c35294-666b-4980-85db-fba92f4be0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
